# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(876, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 120, 101, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CameraButton = QtWidgets.QPushButton(self.layoutWidget)
        self.CameraButton.setObjectName("CameraButton")
        self.verticalLayout.addWidget(self.CameraButton)
        self.PhotoButton = QtWidgets.QPushButton(self.layoutWidget)
        self.PhotoButton.setObjectName("PhotoButton")
        self.verticalLayout.addWidget(self.PhotoButton)
        self.FileButton = QtWidgets.QPushButton(self.layoutWidget)
        self.FileButton.setObjectName("FileButton")
        self.verticalLayout.addWidget(self.FileButton)
        self.Close = QtWidgets.QPushButton(self.layoutWidget)
        self.Close.setObjectName("Close")
        self.verticalLayout.addWidget(self.Close)
        self.ExitButton = QtWidgets.QPushButton(self.layoutWidget)
        self.ExitButton.setObjectName("ExitButton")
        self.verticalLayout.addWidget(self.ExitButton)
        self.DispalyLabel = QtWidgets.QLabel(self.centralwidget)
        self.DispalyLabel.setGeometry(QtCore.QRect(120, 10, 741, 431))
        self.DispalyLabel.setText("")
        self.DispalyLabel.setObjectName("DispalyLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 876, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ExitButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CameraButton.setText(_translate("MainWindow", "摄像头识别"))
        self.PhotoButton.setText(_translate("MainWindow", "图片识别"))
        self.FileButton.setText(_translate("MainWindow", "视频识别"))
        self.Close.setText(_translate("MainWindow", "关闭识别"))
        self.ExitButton.setText(_translate("MainWindow", "退出系统"))
